---
# tasks file for nodejs
#
#yum -y install epel-release
- name: install epel
  yum:
    name: epel-release
    state: installed

#yum -y install nodejs
- name: install nodejs
  yum:
    name: "nodejs-{{ nodejs_ver }}"
    state: installed

#git clone -b server https://github.com/recruit-tech/todo-manager.git /usr/local/src
- name: checkout git repository
  git:
    repo: https://github.com/recruit-tech/todo-manager.git
    dest: "{{ app_dir }}"
    version: server

#npm install
- name: npm install
  npm:
    path: "{{ app_dir }}"
    state: present

#npm install express body-parser
- name: npm install (extra packages)
  npm:
    name: body-parser
    path: "{{ app_dir }}"
    state: present
    version: '1.17.1'

#npm install -g forever
- name: npm install (forever)
  npm:
    name: forever
    global: yes
    state: present
    version: '0.15.3'

- name: check list of nodejs app
  command: forever list
  register: forever_list
  become_user: vagrant
  changed_when: false

#cd /usr/local/src/todo-manager && forever start --uid todo -a ./app.js
- name: start nodejs server
  command: forever start --uid todo -a ./app.js
  args:
    chdir: "{{ app_dir }}"
  become_user: vagrant
  when: "forever_list.stdout.find('todo') == -1"
